### ISSUE TITLE
Planner - compute a command with parameter

### ISSUE THREAD

**Issue by levozavr** [robot-lab/rcs-business-layer#32]
**Модуль по обработке команд с параметрами.**
Сакральный смысл задачи:
Вместо команды **m 0 0 0 0 0 0** может прийти команда вида **m $ID$** 
Для примера:
пришла команда:
`m $cube1$`
planer должен осознать что это команда с параметром и запросить информацию о параметре у  3dscene, получив информацию подставить её в команду вместо параметра 
`$cube1$`
и получить к примеру такую команду:
`m 0 0 0 0 0 0`
Такую команду надо обработать так: отправить реквест **3D scene**, из полученного от неё пакета данных взять координаты объекта **$ID$** и отправить дальше команду с этими координатами

- (!)integrate with  #31

**Comment by levozavr** [comment]
upd: **"m $cube1$ c"**
c - контрольный параметр
@Vasar007

**Comment by Vasar007** [comment]
> upd: **"m $cube1$ c"**
> c - контрольный параметр
> @Vasar007

Будет работать и в текущей реализации.
