### ISSUE TITLE
Planner - compute a command with parameter and shift

### ISSUE THREAD

**Issue by levozavr** [robot-lab/rcs-business-layer#38]
обрабатывать команду следующего вида: 
**"m $cube1$ + X Y Z W P R"**
следующим образом:
отправить запрос к 3d_scene **get $cube1$**
получить от неё данные по кубику  **X1 Y1 Z1 W1 P1 R1**
посчитать координаты конечной точки X1+X Y1+Y Z1+Z W1+W P1+P R1+R
отправить команду с новыми координатами   **"m X2 Y2 Z2 W2 P2 R2"**

**Comment by levozavr** [comment]
upd: **"m $cube1$ + X Y Z W P R ! c"** 
c - контрольный параметр
@Vasar007 ты согласен?

**Comment by Vasar007** [comment]
Да. Доработаю функцию парсинга и запушу в скором времени.

**Comment by Vasar007** [comment]
> upd: **"m $cube1$ + X Y Z W P R ! c"**
> c - контрольный параметр
> @Vasar007 ты согласен?

Да. Доработаю функцию парсинга и запушу в скором времени.
